[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]
